// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PimsPublisher.Infrastructure.IntegrationMessages;

#nullable disable

namespace PimsPublisher.Infrastructure.IntegrationMessages.Migrations
{
    [DbContext(typeof(IntegrationMessageLogContext))]
    [Migration("20230422073103_init-db-with-message-log")]
    partial class initdbwithmessagelog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PimsPublisher.Infrastructure.IntegrationMessages.IntegrationMessageLogEntry", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageId");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("MessageTypeName");

                    b.Property<string>("MessageTypeShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MessageTypeShortName");

                    b.Property<DateTime>("OccurredTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredTime");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayLoad");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("State");

                    b.Property<int>("TimesSent")
                        .HasColumnType("int")
                        .HasColumnName("TimesSent");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TransactionId");

                    b.HasKey("MessageId");

                    b.ToTable("IntegrationMessageLog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
